name: Build the Docker image

on:
  pull_request:
    branches: 
      - "main"
    paths:
      - "Dockerfile"
  push:
    branches: 
      - "main"
    paths:
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout

    - uses: docker/setup-buildx-action@v3
      name: Set up Docker Buildx

    - uses: docker/build-push-action@v6
      name: Build the Docker image
      with:
        context: .
        tags: cgl/text-generation-webui:latest
